name: Build

on:
  cron:
    schedule: "10 0 * * *"
  branches: ["main", "master"]
  pull_request: ["main", "master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout the repo
        run: echo Build Successful.

