########### SECURE CONTEXT START ##############
name: Commit Raw Changes

on:
  workflow_dispatch:
  schedule:
    - cron: '10 0,12 * * *'  # Runs daily at 12:10 AM and 12:10 PM IST

jobs:
  create_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Check for Changes
        run: |
          touch main.txt
          echo "Hello world" > main.txt
        
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Refreshed & Removed Stuff
          commit_user_name: Mahak-2701
          commit_user_email: 131138313+Mahak-2701@users.noreply.github.com
          branch: ${{ github.ref }}
          commit_options: '-a'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GH_TOKEN }}

########### SECURE CONTEXT END ##############